### ISSUE TITLE
Module Isnt Connecting to API & Database ?

### ISSUE THREAD

**Issue by Dev-Networks** [enzu/budgetvm-whmcs#14]
Product Info Displays White Page 500 error.

Also 

Fatal error: Uncaught exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away (SQL: select  from `tblproducts` where `id` = 16 limit 1) (SQL: select  from `tblproducts` where `id` = 16 limit 1)' in /home/admin/web/mysite.com/public_html/client/includes/classes/WHMCS/Terminus.php:0 Stack trace: #0 [internal function]: WHMCS\Terminus->whmcsExceptionHandler(Object(Illuminate\Database\QueryException)) #1 {main} thrown in /home/admin/web/mysite.com/public_html/client/includes/classes/WHMCS/Terminus.php on line 0

Critical Error
 Could not connect to the database.

**Comment by Dev-Networks** [comment]
So to update.  

The issue causing the white screen on product details and this database was a 
  change in my.cnf
 wait_timeout=600 instead of wait_timeout=10

after module was working i noticed a few lines of code that could be improved in hooks.php

 'uri' => './clientarea.php?action=productdetails&id=' . $serviceid . '&customAction=reverse',

you were missing the . in front of the / on clientarea.php so it appends the url 

Hope this helps!

**Comment by oldbathtub** [comment]
It is not a relative link, it is linked absolutely from the root directory
with / ./ would indicate to launch from the current directory the script is
being executed from
