### ISSUE TITLE
Login to Panel as Admin returns blank page

### ISSUE THREAD

**Issue by danperteet** [enzu/budgetvm-whmcs#15]
When clicking on Login to Panel as Admin in the servers page on WHMCS 6.2.2, a blank white page is returned. WHMCS is stock with no modifications, and no modifications to your module. Module is freshly installed per your installation instructions.
Please let me know any info you need me to provide.
Thanks!

**Comment by Dev-Networks** [comment]
Mine has this same issue.  I am working on this as well.

**Comment by reunite-ro** [comment]
have the same issue
