### ISSUE TITLE
V6.x Showing in all products with no module set [bug]

### ISSUE THREAD

**Issue by Fuzzyhosts** [enzu/budgetvm-whmcs#17]
The side menu option is showing in most products that have no module set, to resolve this temporary you have to remove the file hooks.php

**Comment by rihamd2k** [comment]
I am also finding this problem. A quick screenshot: http://prntscr.com/bcjzv4 it's coming on cPanel shared hosting packages.

**Comment by pablojlle** [comment]
Same problem here... the VPS menu is appearing in all my cpanel shared hosting accounts.

**Comment by cincygeek** [comment]
Any word on when this will be updated?

**Comment by kardjo** [comment]
same problem :(
