### ISSUE TITLE
WHMCS 7.1 Issue & WHMCS 7.0

### ISSUE THREAD

**Issue by MKWHosting** [enzu/budgetvm-whmcs#20]
Hi

Is there a working version with WHMCS 7.1 as i keep getting a error on a clients end

Error: Malformed API Function

also doing it on VPS,Cloud Servers, Dedicated Servers

**Comment by dennopro** [comment]
I have the same issue; did you find a work around @MKWHosting ?

**Comment by MKWHosting** [comment]
@dennopro 

hi no have not found any work around of this at all

**Comment by Littlemurder109** [comment]
I have the same issue mine only happen on Cloud Servers and Dedicated Servers my vps users don't have the issue.

**Comment by oldbathtub** [comment]
This is an API related error, I will try and get a patch pushed out for it shortly

**Comment by MKWHosting** [comment]
@bdwarr6 Hi can we get a update on the api patch

**Comment by rajkavinchetty** [comment]
BudgetVM, Please make an update for WHMCS 7.0 and 7.1, Looking forward for that :)

**Comment by MKWHosting** [comment]
You can close this. since you guys seem not to care about us i left you guys and move to a new company and closed over 150 servers with your company

**Comment by devalmount** [comment]
not respond from staff ^^

**Comment by geoker** [comment]
yup, we're also looking to move away from budget vm. The lack of api features/whmcs module/ and automation is the key reason.
