### ISSUE TITLE
problem show manage VPS on every detail cpanel hosting

### ISSUE THREAD

**Issue by kardjo** [enzu/budgetvm-whmcs#22]
I just realized, it turns out in every detail WHMCS client cpanel hosting, managed VPS detail emerged from the budget VM, which should only appear in detail VPS only.

The following screenshot of me: http://prntscr.com/e36stq

**Comment by MKWHosting** [comment]
Hi

i have fixed this by removing the hooks.php as a temp fix

**Comment by kardjo** [comment]
hi @MKWHosting,
thanks you for help

**Comment by mediavista** [comment]
@MKWHosting @kardjo should i remove hooks.php? does the module work if i remove hooks.php?

**Comment by kardjo** [comment]
@mediavista, module work fine...
