### ISSUE TITLE
Module not working with hetzner

### ISSUE THREAD

**Issue by shoquebd** [enzu/budgetvm-whmcs#7]
I'm having issues with hetzner vserver which using NAT IP. Recently after moved on hetzner, budgetvm module client's product details page showing 500 server error. Can I expect any solution?

**Comment by Dev-Networks** [comment]
Same problem Im having

**Comment by Dev-Networks** [comment]
I'm having similar issue with the product details page showing 500 server error.

I believe its a CSRF token or lack of that is causing the error but im not exactly sure.

Will do more research on this soon.

**Comment by shoquebd** [comment]
This is not fault of the module! I got it solve myself by increasing long_query_time in etc/my.cnf file and problem is solved.
