### ISSUE TITLE
Missing Variable Service for XEN , whmcs modules

### ISSUE THREAD

**Issue by oldbathtub** [enzu/budgetvm-whmcs#8]
<div class='row'>
  <div class='col-md-2'>
    Client: 37778
  </div>
  <div class='col-md-2'>
Hello,

I have a little problem about WHMCS module that I plug in version 6.
for OpenVZ no problem, but for xen vps there is a slight problem.
You can see a screenshot here,,,

Missing Variable for xen http://prntscr.com/98c1i3

Not problem for OpenVZ http://prntscr.com/98c540

What should be improved?

Thanks
  </div>
</div>

**Comment by MKWHosting** [comment]
i have the same issue

**Comment by dean2016** [comment]
Is there a timeline when this might be resolved. Mine not working in Client Area or admin (OpenVZ)
